version: '3'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./.streamlit:/app/.streamlit
      - ./descargas:/app/descargas
    restart: unless-stopped 