version: '3.3'

services:
  streamlit:
    build: .
    container_name: dashboard-operaciones
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ~/streamlit-app/dashboard_operaciones:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_SERVER_ADDRESS=146.190.187.4
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=200
      - STREAMLIT_THEME_BASE=light
      - STREAMLIT_LOGGER_LEVEL=info
      - STREAMLIT_CLIENT_TOOLBAR_MODE=minimal
      - STREAMLIT_SERVER_ENABLE_CORS=true
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    mem_limit: 2.5g
    mem_reservation: 1g
    cpus: 1.2
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.6
    depends_on:
      - streamlit
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  dashboard-network:
    driver: bridge