[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
maxMessageSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"

[runner]
magicEnabled = false
fastRerenderEnabled = false

[client]
showErrorDetails = true
toolbarMode = "minimal" 