[server]
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = true
maxMessageSize = 200
enableStaticServing = true
runOnSave = false
headless = true

[browser]
serverAddress = "146.190.187.4"
gatherUsageStats = false
serverPort = 8501

[global]
developmentMode = false
showWarningOnDirectExecution = false
dataFrameSerialization = "arrow"

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
magicEnabled = true
fastReruns = true
postScriptGC = true
handleKernelCrash = true 